sudo: required
language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"

install:
 - sudo apt-get install swig -y
 - pip install --upgrade setuptools pip
 - pip install -r tests-requirements.txt
 - pip install -e .
script: python -m unittest discover -v

matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.5"
