language: python
python:
 - "2.7"
 - "3.3"

install:
 - pip install --upgrade setuptools
 - python setup.py develop
script: python setup.py test
notifications:
    email: false
    irc: false
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - python: "3.3"
    - python: "2.6"
